### ISSUE TITLE
The auto delete feature misses a couple of things.

### ISSUE THREAD

**Issue by minanagehsalalma** [aydinnyunus/Keylogger#1]
![Screenshot_2020-03-13-18-08-27-1](https://user-images.githubusercontent.com/20546638/76638884-e2ce0700-6555-11ea-9e6a-47daae22d41f.png)

Also what if someone takes a copy of it first ?

**Comment by aydinnyunus** [comment]
According to your text file name changing problem and race condition problem,As a solution I add new perspective to Self-Destruct part again.I change this part to if program is closeable (its open) close and delete it.It's fixed for if target rename file now it does not matter.
And yes the target will save the file but until the target find the file and save it.The mail is already forwarded.
And I don't understand the last sentence "Also what if someone takes a copy of it first ?" what does it mean ? Did you mean If someone steal the repository ?

**Comment by minanagehsalalma** [comment]
@aydinnyunus i have posted it to reddit and users think that the tool self destruct is super stupid... here is some comments.
The second issue is one from them.
![Screenshot_2020-03-13-22-08-52-1](https://user-images.githubusercontent.com/20546638/76656056-7532d280-6577-11ea-9aec-a9ce9e0e1c89.png)
Another idea is to encrypt the data and upload it to something like pastebin instead here a one that does so
https://github.com/brannondorsey/letterpress

Or send a data to an http server.

**Comment by minanagehsalalma** [comment]
> "Also what if someone takes a copy of it first ?

I meant the file....i think you can change that from the file permissions.

**Comment by aydinnyunus** [comment]
I found  the reddit post now.I examine all comments now.I will consider them all. A very good keylogger is waiting for you.

**Comment by minanagehsalalma** [comment]
> A very good keylogger is waiting for you.

@aydinnyunus i will be waiting for it ;)
