### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by ayashgupta** [aydinnyunus/Keylogger#12]
Hi, I am a little confused about where to change the password and email.
Is it at the bottom of the whole code where it is written: YourMail and YourPassword or in the middle.

**Comment by YaminiRam2020** [comment]
You have to create your own dummy email and set those credentials there in that code. 
Use Gmail.
Don't forget to turn on access for less secure apps.

If it solves the issue please like me

**Comment by jay917812** [comment]
Which place to set dummy email explain in detail

**Comment by kason12335** [comment]
> You have to create your own dummy email and set those credentials there in that code. Use Gmail. Don't forget to turn on access for less secure apps.
> 
> If it solves the issue please like me

You just made it work for me thanks!

**Comment by aydinnyunus** [comment]
I added new solution. Please look at README.md for using temp mail.
