### ISSUE TITLE
Could you please share the source code of the .exe file?

### ISSUE THREAD

**Issue by Bertil1** [aydinnyunus/Keylogger#13]

**Comment by omtoi101** [comment]
the exe is just the python file compiled I think

**Comment by elusieemmanuel** [comment]
How do I put my own Gmail details in the exe file since it's been compiled? And how do I compile mine?

**Comment by omtoi101** [comment]
> How do I put my own Gmail details in the exe file since it's been compiled? And how do I compile mine?

you dont just use the .py file

**Comment by elusieemmanuel** [comment]
I don't understand, if it's not the py file. Which other file then?

**Comment by aydinnyunus** [comment]
You can use keylogger.py to generate .exe file.
