### ISSUE TITLE
Connection unexpectedly closed

### ISSUE THREAD

**Issue by vamsi-prem-tarun** [aydinnyunus/Keylogger#14]
i am getting this error when running keylogger.py file.the error is

 raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

please help me out

**Comment by Majdoulineait** [comment]
Hello, same problem here!
I have tried to connect on different ports 25, 465 but none of them work.
Maybe it is a problem of the timeout, maybe trying to increase it maybe let the issue disappear but I don't think so.
Maybe the problem come from the server that is not responding.
