### ISSUE TITLE
self-destruct prevented by renaming

### ISSUE THREAD

**Issue by MvonK** [aydinnyunus/Keylogger#2]
Issue: When I run the keylogger, then rename the keylogger file, self-destruct will trigger, however, since the name is hardcoded, it will not selfdestruct. 

Possible solution: adding `f = open (__file__, "r")` at the code beginning should prevent renaming file while running (tested on windows)

Suggestions: Change all hard-coded names to __file__, which is full path of current running script.

**Comment by aydinnyunus** [comment]
I add this code to Self-Destruct part again.I change this part to if program is closeable (its open) close and delete it and it's fixed for renamed.
