### ISSUE TITLE
compil fail

### ISSUE THREAD

**Issue by antoine-vaxelaire** [aydinnyunus/Keylogger#22]
Traceback (most recent call last):
  File "C:\wamp64\www\labo\Keylogger\keylogger.py", line 129, in <module>
    keylogger.run()
  File "C:\wamp64\www\labo\Keylogger\keylogger.py", line 101, in run
    keyboard_listener = keyboard.Listener(on_press=self.save_data)
NameError: name 'keyboard' is not defined

**Comment by VHAE04** [comment]
the same problem me

**Comment by imYashGupta** [comment]
same issue. i am not a py dev, can't figure out

**Comment by VHAE04** [comment]
> 

:V  try use another Keylogger in github or here the guy help me fix it https://stackoverflow.com/questions/51381763/python-3-6-pynput-nameerror-name-keyboard-is-not-defined

**Comment by Xprogrammer777** [comment]
> the same problem me

Well old issue, it's just because you need to install keyboard.

**Comment by VHAE04** [comment]
> > the same problem me
> 
> Well old issue, it's just because you need to install keyboard.

i tryed install kayboard but it not working

**Comment by Xprogrammer777** [comment]
> > > the same problem me
> > 
> > Well old issue, it's just because you need to install keyboard.
> 
> i tryed install kayboard but it not working

....
OK, I will see later and check if the problem come from the python code... But I dontm't think so...

**Comment by aydinnyunus** [comment]
I added requirements.txt use `pip install -r requirements.txt` command.
