### ISSUE TITLE
"keyboard" is not definied

### ISSUE THREAD

**Issue by ardakaraosmanoglu** [aydinnyunus/Keylogger#24]
<img width="650" alt="Screen Shot 2021-12-13 at 20 55 14" src="https://user-images.githubusercontent.com/77415587/145871276-9d18a865-c8e4-4601-852f-f2cfc8e8d1a5.png">
What is the problem? How can I solve this?

**Comment by ImanJ14** [comment]
same. i think python version 3.9.6 works without error

**Comment by ardakaraosmanoglu** [comment]
same on version 3.9.6

**Comment by ImanJ14** [comment]
this works on my main pc with version 3.9.6, but i reinstaled this script with python 3.9.6 on a win 10 vm and it came with that error. idk y

**Comment by jhoto123** [comment]
Does anyone have a solution to this error?

**Comment by kantar0** [comment]
Hello, I have the same problem, has anyone found a solution for windows?

**Comment by santiagocss** [comment]
> For windows whats the solution?

pip install pynput

**Comment by aydinnyunus** [comment]
requirements.txt added use `pip install -r requirements.txt`
