### ISSUE TITLE
I can't install the required packages

### ISSUE THREAD

**Issue by X-Omega** [aydinnyunus/Keylogger#25]
when I type on my terminal:
pip install logging(for example)

it say: ERROR: Could not find a version that satisfies the requirement logging (from versions: 0.4.9.6)
ERROR: No matching distribution found for logging

like the package doesn't exist

and it's the same with 4~5 packages required for the script

**Comment by aydinnyunus** [comment]
requirements.txt added.

logging library is built-in.
