### ISSUE TITLE
How to create an exe 

### ISSUE THREAD

**Issue by PGSCOM** [aydinnyunus/Keylogger#32]
How can I create an exe file for run it in a pc without python?

**Comment by PGSCOM** [comment]
I look in #19 @aydinnyunus delete the .exe file of [186b60adb0f49d69dadcda7ba03d1a66b4e336a1](https://github.com/aydinnyunus/Keylogger/commit/186b60adb0f49d69dadcda7ba03d1a66b4e336a1) and the first commit of the .exe file is [4d3d3abef948e2f25fc81995bf2d9c9709989cd4](https://github.com/aydinnyunus/Keylogger/commit/4d3d3abef948e2f25fc81995bf2d9c9709989cd4)

**Comment by MaciejkaG** [comment]
use pyinstaller or pyexe
