### ISSUE TITLE
How to convert it from .py to .exe

### ISSUE THREAD

**Issue by Georger2323** [aydinnyunus/Keylogger#4]
Is it possible to convert this to an executable? I've already tried it and when clicking on the executable, the command window opens and closes immediately and no email is sent to my inbox.

**Comment by aydinnyunus** [comment]
Try to create setup.py file for convert operation.Look these solutions: https://stackoverflow.com/questions/41570359/how-can-i-convert-a-py-to-exe-for-python

**Comment by Georger2323** [comment]
Already tried that with no luck. However, when I try to test a simple program it works. There's something in the code that prevents the window from remaining open.

**Comment by aydinnyunus** [comment]
Do you apply the all of the READ.ME ?

**Comment by Georger2323** [comment]
The .py file works as expected. The problem is when I convert it to .exe

**Comment by Georger2323** [comment]
Would you mind testing it yourself please?

**Comment by aydinnyunus** [comment]
I test again and it's working.Maybe you get "Connection unexpectedly closed" warning.Try this solutions : https://stackoverflow.com/questions/17759860/python-2-smtpserverdisconnected-connection-unexpectedly-closed

**Comment by Georger2323** [comment]
As I said before the emails are sent successfully when I run the .py file.
Anyway, I will look into the issue another time. Thank you for your time
