### ISSUE TITLE
I'm unable to run the program.

### ISSUE THREAD

**Issue by arewageek** [aydinnyunus/Keylogger#48]
After installing the required dependencies in the requirments.txt files. I'm unable to run the keylogger.py file

I always get an error stating:

```
Traceback (most recent call last):
  File "/home/arewageek/dev/py/loggers/Keylogger/keylogger.py", line 143, in <module>
    keylogger.run()
  File "/home/arewageek/dev/py/loggers/Keylogger/keylogger.py", line 115, in run
    keyboard_listener = keyboard.Listener(on_press=self.save_data)
NameError: name 'keyboard' is not defined
```
![image](https://github.com/aydinnyunus/Keylogger/assets/79693099/7d2e1b66-a30d-4a02-b924-3c3eeb12f78b)

**Comment by Sayadat99** [comment]
Install all dependencies by running the below commands one after another, then try

pip install pynput==1.7.3
pip install pyscreenshot==0.5.1
pip install sounddevice==0.4.3
pip install Pillow==9.3.0

**Comment by arewageek** [comment]
Thank you for your support. Issues were resolved.
