### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ash0x0** [aydinnyunus/Keylogger#6]
Thank you for the great work @aydinnyunus. Your repo doesn't include a license and given [copyright rules](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license) standard copyright applies which means no one can build on this without your explicit permission. I'm working on a small project that I'm publishing under Apache 2.0 and I'd love to use your code but I can't given the fact there's no license. Please add a License so everyone can build on this amazing script.

**Comment by aydinnyunus** [comment]
Thank you for advice.I create License with Apache 2.
