### ISSUE TITLE
n

### ISSUE THREAD

**Issue by neew83** [aydinnyunus/Keylogger#8]
bbbbb

**Comment by Se9y** [comment]
أرسل 6 9 إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail:

[image: شعار Gmail]Re: [aydinnyunus/Keylogger] n (#8) <https://confidential-mail.google.com/msg/AJd0jO18S6mzk4d1juoBdRCmYTIZw3S-mUNx7109NZHEZT9-Am4qnNxdPIX8MCan5F4zhO1m4pPSP1yaAtol3jVKiJJyTUJhQKd_2fYPP3MUTcAO3fb7z2PHNOOtsJYOw-o0HqNmCss2erAhVhd996f_yNwrm-y17aAFEjAnF1HbULCRdgwMuPxLJat-c2InFjHqJk8f340vZ1gJsA==>

تم إرسال هذه الرسالة يوم 21‏/03‏/2021 الساعة 4:20:31 ص غرينتش-7
يمكنك فتحه بالنقر على الرابط أدناه. ولا يعمل هذا الرابط إلا مع ***@***.***

عرض الرسالة الإلكترونية <https://confidential-mail.google.com/msg/AJd0jO18S6mzk4d1juoBdRCmYTIZw3S-mUNx7109NZHEZT9-Am4qnNxdPIX8MCan5F4zhO1m4pPSP1yaAtol3jVKiJJyTUJhQKd_2fYPP3MUTcAO3fb7z2PHNOOtsJYOw-o0HqNmCss2erAhVhd996f_yNwrm-y17aAFEjAnF1HbULCRdgwMuPxLJat-c2InFjHqJk8f340vZ1gJsA==>

يمنحك "الوضع السري في Gmail" مزيدًا من التحكُّم في الرسائل التي تُرسِلها. ربما اختار المُرسِل تحديد وقت انتهاء الصلاحية أو إيقاف الطباعة أو إعادة توجيه رسالة أو تتبّع الوصول إلى هذه الرسالة. مزيد من المعلومات <https://support.google.com/mail/answer/7674059>
Gmail: خدمة بريد إلكتروني مُقدَّمة من Google
يخضع الاستخدام لـ سياسة خصوصية Google <https://myaccount.google.com/privacypolicy?hl=ar>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
لقد استلمت هذه الرسالة لأن أحدهم أرسل إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail.
[image: شعار Google]

**Comment by Se9y** [comment]
رمز التحقق التابع لك في Google هو 055837.

**Comment by neew83** [comment]
error

**Comment by Se9y** [comment]
رمز التحقق التابع لك في Google هو 609274.

**Comment by Se9y** [comment]
رمز التحقق التابع لك في Google هو 692217.

**Comment by Se9y** [comment]
رمز التحقق التابع لك في Google هو 782062.

**Comment by Se9y** [comment]
رمز التحقق التابع لك في Google هو 547590.

**Comment by Se9y** [comment]
رمز التحقق التابع لك في Google هو 818418.
